# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
    
jobs:
  generate-version:
    runs-on: ubuntu-latest
    
    permissions: # to publish the new tag to github
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Github Tag Bump
      id: tag_bump
      uses: anothrNick/github-tag-action@1.67.0
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        INITIAL_VERSION: 1.0.11
        DEFAULT_BUMP: patch # 1.0.x

    outputs: 
      new_version: ${{ steps.tag_bump.outputs.new_tag }} # store the generated tag
          
    
  package-and-publish-common:
    runs-on: ubuntu-latest
    needs: generate-version # this job requires this to be completed

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
    - name: Pack
      run: |
        dotnet pack src/Play.Common/ \
          --configuration Release \
          -p:PackageVersion=${{ needs.generate-version.outputs.new_version }} \
          -p:RepositoryUrl=https://github.com/${{ github.repository_owner }}/play.common \
          -o packages

    - name: Publish
      run: dotnet nuget push packages/*.nupkg
